Update docs
conda/conda pull request #10329
Opened 2020-11-01 22:20 UTC by mattip

- Add blurb about PyPy
- Change some examples of python use to python3.9
- Soften the commitment about latest Python versions
- Mention the commercial nature of the default channel

The last point could use some careful review: I am not sure I got the content and tone right.

2020-12-07 10:01 UTC, mattip commented
Any thoughts on this PR?

2021-01-07 19:26 UTC, cjmartian commented
@anaconda-issue-bot check

2021-05-31 16:14 UTC, jezdez commented
@chenghlee Could you take a closer look at the documentation changes here if they match what Anaconda's policy is at the moment?

2021-06-02 16:17 UTC, chenghlee requested changes

2021-06-02 17:30 UTC, mattip commented on docs/source/user-guide/tasks/manage-channels.rst
> +may require a license for commercial use.
changed to "and the various terms of service for their use"

2021-06-02 17:31 UTC, mattip commented on docs/source/user-guide/install/download.rst
> +  non-commercial use.
adopted

2021-06-02 17:31 UTC, mattip commented on docs/source/user-guide/concepts/channels.rst
> +a commercial license. The ``conda-forge`` channel is free for all to use.
adopted

2021-06-02 17:31 UTC, mattip commented
changes made. CI is waiting for a maintainer to approve running

2021-06-07 11:31 UTC, chenghlee approved these changes

2021-06-07 11:31 UTC, merged

2021-06-07 12:02 UTC, mattip commented on docs/source/user-guide/tasks/manage-python.rst
> +    conda config conda config --add channels confa-forge
grr, typo. Will do another PR to fix it