Fix channel args cli
conda/conda pull request #10735
Opened 2021-06-20 15:54 UTC by ericpre

Fix #10732.

2021-06-20 15:57 UTC, ericpre commented on tests/base/test_context.py
> +        assert context.channels == ('conda-forge', 'other')
These tests check the current behaviour and pass without this PR.

2021-06-20 15:58 UTC, ericpre commented on tests/base/test_context.py
> +        assert context.channels == ('conda-forge', )
This test checks for the fix.

2021-06-20 16:06 UTC, ericpre commented
At first, it was not clear to me when the `'defaults'` channel need to be added but based on the conda documentation, I added to tests cover the different cases and it should be good now.

2021-06-20 16:09 UTC, ericpre commented on conda/base/context.py
>          if self._argparse_args and 'channel' in self._argparse_args:
This `if` block is necessary to cover the case in `test_specify_channels_cli_adding_defaults_no_condarc`.

2021-06-22 13:49 UTC, jezdez requested changes
This looks good to me in general, here are just some suggestions around using docstrings in the test functions so the pytest traceback has the full context. Minor fixes around tuple syntax and docstring content as well.

2021-06-22 13:49 UTC, jezdez commented on tests/base/test_context.py
> +        # 'defaults' should not be added
```suggestion
        """
        When the channel have been specified in condarc, these channels
        should be used along with the one specified
        In this test, the given channel in cli is different from condarc
        'defaults' should not be added
        """
```

2021-06-22 13:49 UTC, jezdez commented on tests/base/test_context.py
> +        # should be used along with the one specified
```suggestion
        """
        When the channel have been specified in condarc, these channels
        should be used along with the one specified
        """
```

2021-06-22 13:49 UTC, jezdez commented on tests/base/test_context.py
> +        # should be present when specifying channel in the cli
```suggestion
        """
        When the channel haven't been specified in condarc, 'defaults'
        should be present when specifying channel in the cli
        """
```

2021-06-22 13:49 UTC, jezdez commented on tests/base/test_context.py
> +        # no channels provided in cli
```suggestion
        """
        Test when no channels provided in cli, but some in condarc
        """
```

2021-06-22 13:49 UTC, jezdez commented on tests/base/test_context.py
> +        # no channels provided in cli
```suggestion
        """
        Test when no channels provided in cli
        """
```

2021-06-23 07:14 UTC, ericpre commented
Thanks @jezdez for the review, I have applied your suggestions!

2021-06-23 08:27 UTC, jezdez approved these changes
Thanks @ericpre!

2021-06-23 08:27 UTC, merged