plugins: add plugin mechanism barebones
conda/conda pull request #11201
Opened 2022-02-07 19:54 UTC by FFY00

2022-02-07 19:54 UTC, FFY00 commented
@jezdez could you ping the documentation person on anaconda's side? Thanks!

2022-02-08 10:40 UTC, jezdez commented
Hey @kathatherine, would you mind taking a quick look if that sounds fine for you?

2022-02-08 15:27 UTC, kathatherine requested changes
Looks good to me other than my one comment.

2022-02-08 15:27 UTC, kathatherine commented on docs/source/plugin-api/index.rst
> +entrypoints. You may refeer to pluggy_'s documentation for full description of
"for a full description..." Missing the article "a" there.

2022-02-16 16:34 UTC, jezdez approved these changes
Just a minor nit

2022-02-16 16:34 UTC, jezdez commented on docs/source/plugin-api/index.rst
> +entrypoints. You may refeer to pluggy_'s documentation for full description of
Let's add a link to https://packaging.python.org/en/latest/specifications/entry-points/ for the Python entry points docs.

2022-02-21 16:01 UTC, jezdez approved these changes

2022-02-21 16:24 UTC, jezdez commented on docs/source/plugin-api/index.rst
> +entrypoints. You may refeer to pluggy_'s documentation for a full description of
```suggestion
Plugins are implemented via pluggy_ and discovered using
`Python package entrypoints`_. You may refeer to pluggy_'s documentation for a full description of
```

2022-02-21 16:25 UTC, jezdez commented on docs/source/plugin-api/index.rst
> +register and register your plugin under the ``conda`` entrypoint namespace.
```suggestion
Plugins are implemented via pluggy_ and discovered using
`Python package entrypoints`_. You may refeer to pluggy_'s documentation
for a full description of its features, but in summary, you will want to define
the hooks you want to register and register your plugin under the ``conda``
entrypoint namespace.
```

2022-02-21 16:26 UTC, jezdez commented on docs/source/plugin-api/index.rst
> +.. _pluggy: https://pluggy.readthedocs.io/en/stable/
```suggestion
.. _pluggy: https://pluggy.readthedocs.io/en/stable/
.. _`Python package entrypoints`: https://packaging.python.org/en/latest/specifications/entry-points/
```

2022-02-21 17:32 UTC, kathatherine approved these changes

2022-02-21 18:05 UTC, jezdez commented on docs/source/plugin-api/index.rst
> +       entry_points={"eggsample": ["my_conda_plugin = my_plugin"]},
> I'm currently assuming "eggsample" is some sort of clever pun and not a mistake?

Hah, yeah, eggs are the name of the file format that Python packages used to distributed as (from the [Monty Python "SPAM" sketch](https://www.youtube.com/watch?v=zLih-WQwBSc)) 🤷🏻

2022-02-21 18:07 UTC, jezdez commented on docs/source/plugin-api/index.rst
> +       entry_points={"eggsample": ["my_conda_plugin = my_plugin"]},
BTW the new format is called "wheels" for ~"wheel of cheese" following the [Monty Python "Cheese shop" sketch](https://www.youtube.com/watch?v=Hz1JWzyvv8A) 😬

2022-02-21 18:34 UTC, FFY00 commented on docs/source/plugin-api/index.rst
> +       entry_points={"eggsample": ["my_conda_plugin = my_plugin"]},
Yeah, but we should rename this to something more intuitive. I based this off the pluggy documentation and forgot to change this :sweat_smile: 

> Hah, yeah, eggs are the name of the file format that Python packages used to be distributed as (from the [Monty Python "SPAM" sketch](https://www.youtube.com/watch?v=zLih-WQwBSc)) 🤷🏻

This is why you will find `spam` in the examples all over the standard library documentation :wink:

2022-02-21 18:42 UTC, kathatherine commented on docs/source/plugin-api/index.rst
> +       entry_points={"eggsample": ["my_conda_plugin = my_plugin"]},
Amazing. My dad raised me on Monty Python, but I haven't watched in ages. I should remedy this.

2022-02-21 18:48 UTC, jezdez commented on docs/source/plugin-api/index.rst
> +       entry_points={"eggsample": ["my_conda_plugin = my_plugin"]},
Maybe this would be generic enough?
```suggestion
       entry_points={"conda": ["my-conda-plugin = my_plugin"]},
```

2022-02-21 18:53 UTC, kathatherine commented on docs/source/plugin-api/index.rst
> +       entry_points={"eggsample": ["my_conda_plugin = my_plugin"]},
Works for me.

2022-02-23 19:17 UTC, merged