Check conda PS1 hook before calling it
conda/conda pull request #11374
Opened 2022-03-28 14:55 UTC by wulmer

We faced some issues with the PowerShell hook which gets installed via `conda init`. When a user uninstalls Anaconda, the hook isn't removed automatically which then leads to errors each time when the user opens a new PowerShell instance.

The patch in this PR simply adds a test for the conda executable 
**so that the shell hook is only called if conda exists**.

2022-03-30 00:07 UTC, kenodegard requested changes
@wulmer thank you for this contribution!

Since this check is equally valid for all of the other shells would you be able to make the applicable changes for those shells as well?

2022-04-16 15:19 UTC, wulmer commented
> @wulmer thank you for this contribution!
> 
> Since this check is equally valid for all of the other shells would you be able to make the applicable changes for those shells as well?

Hi @kenodegard , sure, I'll try to fix this for other shells as well, however this might take some time...

2022-09-16 07:49 UTC, wulmer commented on conda/core/initialize.py
> +        (& "{conda_exe}" "shell.powershell" "hook") | Out-String | ?{{$_}} | Invoke-Expression
@kenodegard : we have had an issue today where `Test-Path "{conda_exe}"` still worked as `conda.exe` existed, but Python couldn't be executed due to some missing files/DLLs (it was a broken installation).

However this led to other scripts failing during PS1 initialization, as the line above then failed: conda was there, and could be called, but Python crashed → the whole profile script was treated as failed.

Should I add an extra layer of safety here and catch exceptions occurring during this conda hook call?

2022-09-19 07:06 UTC, wulmer commented on conda/core/initialize.py
> +        (& "{conda_exe}" "shell.powershell" "hook") | Out-String | ?{{$_}} | Invoke-Expression
At the moment, I am using this code:

```powershell
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
If (Test-Path "C:\Program Files\Anaconda3\Scripts\conda.exe") {
    try {
        (& "C:\Program Files\Anaconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
    }
    catch {
        # some verbose warning message which tells the user
        # what to do, i.e. to reinstall Anaconda.
    }
}
#endregion
```

2022-09-23 17:44 UTC, kenodegard requested changes
This looks good as is, it's just missing a news snippet.

Let's wait on adding any more checks to these shell interfaces. We're currently ramping up work on the plugin framework (https://github.com/conda/conda/issues/11820), and we expect all of these shell interfaces to be split into separate plugins in the near future.

2022-10-07 15:24 UTC, kenodegard approved these changes
@wulmer thanks for working on this!

2022-10-07 15:26 UTC, merged