Separate `SSLError` from `HTTPError`
conda/conda pull request #11564
Opened 2022-06-21 19:17 UTC by kenodegard

### Description

Previously `SSLErrors` were grouped with `HTTPErrors` and hence became more difficult to diagnose since we'd receive a non-obvious HTTP 000 error. This change defined a new `CondaSSLErrors` and passes through the SSLError for further diagnosis.

See #11367 (not a complete solution as HTTP 000 is still possible).

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/master/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2022-07-18 12:03 UTC, jezdez requested changes
This increases the number of our test runs drastically just for one test. Can you think of another way that would successfully monkeypatch this, so the tests are run in place and we don't have as much test matrix sprawl?

2022-07-20 18:01 UTC, kenodegard commented
@jezdez I agree, I dislike that I had to implement the tests this way, but I don't see a simple alternative. Trying to properly mock the import as part of the regular unit test suite is not straightforward. The problem is that `conda` gets imported as part of pytest startup (https://github.com/conda/conda/blob/6ed9db722e95234b618e5ec36825c3673ffbf302/tests/__init__.py) so even if the no SSL test is the very first test run, conda has already been imported making any mocking very convoluted.

2022-07-22 13:59 UTC, dholth commented on tests/core/test_subdir_data.py
> +    url = "https://www.fake.fake/fake/fake/noarch"
this url might be fake

2022-07-25 14:15 UTC, jezdez approved these changes

2022-07-25 14:15 UTC, merged