Fail with a readable warning if PackageCacheRecords are missing
conda/conda pull request #11591
Opened 2022-06-29 12:36 UTC by timhoffm

### Description

I recently got tripped up by a broken channel that triggered the assertion.

However, the error is not quite helpful to the user. Even from the code context it's hard to understand what the issue is.

This PR replaces the `assert` statement by  an `AssertionError` with a proper message. I've chosen `AssertionError` to raise the same exception type. Let me know if you would like to raise a different exception here.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/master/news/TEMPLATE)) for the next release's release notes? - *Not a significant change*
     
- [x] Add / update necessary tests? - *I believe setting up a test for this is hard. If you have a good idea how to test this, I'm happy to include it.*
- [x] Add / update outdated documentation? - *Does not apply*

2022-06-29 12:47 UTC, timhoffm commented
CLA is signed.

2022-07-05 13:13 UTC, jezdez commented
@conda-bot check

2022-07-05 22:47 UTC, timhoffm commented
> Please add a test to cover the detailed assertion and add a news item. Thank you!

Will do. It may take some days until I can come around to this.

2022-09-07 10:10 UTC, timhoffm commented
Ping @jezdez. I've added a test and news item. Please check whether they are ok.

I have users for whom the assertion gets triggered, and it's quite difficult to find out what is wrong. It would be great if we can get this improved error messaging merged. Thanks in advance!

2022-09-12 15:15 UTC, kenodegard requested changes
Most of this appears to be black reformatting noise, looks good to go with an update to the news snippet

2022-09-12 15:15 UTC, kenodegard commented on news/11591-readable-error-message-if-packagecacherecords-missing
> +  packages not being in the cache.
```suggestion
  packages not being in the cache. (#11591)
```

2022-09-12 15:19 UTC, kenodegard commented on tests/test_misc.py
> +    self.assertEqual(cache_fn_url(url), "e42afea8.json")
```suggestion
def test_cache_fn_url():
    url = "http://repo.continuum.io/pkgs/pro/osx-64/"

    # implicit repodata.json
    assert cache_fn_url(url) == "7618c8b6.json"
    
    # explicit repodata.json
    assert cache_fn_url(url, "repodata.json") == "7618c8b6.json"
    
    # explicit current_repodata.json
    assert cache_fn_url(url, "current_repodata.json") == "8be5dc16.json"
    
    url = "http://repo.anaconda.com/pkgs/pro/osx-64/"
    assert cache_fn_url(url) == "e42afea8.json"
```

2022-09-12 18:27 UTC, jezdez commented
precommit.ci autofix

2022-09-14 15:33 UTC, jezdez approved these changes

2022-09-15 19:19 UTC, kenodegard approved these changes

2022-09-29 17:41 UTC, merged