Add conda binary to $PATH first before initialize.
conda/conda pull request #11740
Opened 2022-08-21 10:20 UTC by mpotane

### Description
Cannot invoke conda init fish because fish doesn't auto add the binary to $PATH #8590

### Checklist - did you ...

- [x] Add / update documentation?

2022-08-21 10:26 UTC, mpotane commented
> We require contributors to sign our [Contributor License Agreement](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement) and we don't have one on file for @mpotane.
> 
> In order for us to review and merge your code, please e-sign the [Contributor License Agreement PDF](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement). We then need to manually verify your signature. We will ping the bot to refresh the PR status when we have confirmed your signature.

done signing 😁

2022-08-22 14:05 UTC, jaimergp commented on docs/source/user-guide/install/linux.rst
> +      fish_add_path path/to/bin
```suggestion
      fish_add_path path/to/condabin
```

It's best to add only the `condabin` directory, which is designed to contain only conda binaries, and not other stuff that might be installed in `base` (e.g. `python`).

2023-03-29 20:12 UTC, jezdez commented
@conda-bot check

2023-04-02 09:26 UTC, mpotane commented
pre-commit.ci autofix

2023-05-04 10:07 UTC, travishathaway requested changes
Hi @mpotane,

Sorry for the late turn around on this 🙃. I made one suggestion to your documentation changes. I think if we incorporate that, this pull request will be ready to merge.

2023-05-04 10:07 UTC, travishathaway commented on docs/source/user-guide/install/linux.rst
> +      fish_add_path path/to/condabin
```suggestion
      fish_add_path <conda-install-location>/condabin
```

I think this makes it a little more clear that the `condabin` folder is located where conda itself was installed.

2023-05-30 12:39 UTC, travishathaway approved these changes

2023-05-30 12:40 UTC, merged

2023-06-07 11:16 UTC, jezdez commented
@travishathaway @mpotane https://github.com/conda/conda/pull/12070#issuecomment-1578954925 applies here, `fish_add_path` is a feature that was only added in fish 3.2.0 which may not be available in all Linux distributions yet. This is related to the unresolved #11079 as well.