Modify `ExceptionHandler.write_out` to Properly Show Errors
conda/conda pull request #11746
Opened 2022-08-22 20:33 UTC by beeankha

Addresses https://github.com/conda/conda/issues/11689, first brought up in [this comment](https://github.com/conda/conda/pull/11435#pullrequestreview-1059455307).

This code change ensures that 

Also tidied up the `ExceptionHandler._ask_upload` method where it asks whether or not the user would like to send an error report.

2022-08-22 21:01 UTC, kenodegard requested changes
This also needs a news snippet.

2022-08-22 21:01 UTC, kenodegard commented on conda/exceptions.py
> +        logger.info(content_str)
I'd also get rid of these temp vars:

```python
        getLogger("conda.stderr").info("\n".join(content))
```

2022-08-23 13:51 UTC, kenodegard requested changes

2022-08-23 13:51 UTC, kenodegard commented on conda/exceptions.py
> +
```suggestion
```

2022-08-23 14:13 UTC, kenodegard approved these changes
Looks good! Let's get some other eyes on this before merging.

2022-08-24 18:31 UTC, chenghlee approved these changes

2022-08-24 19:22 UTC, merged