Avoid a specific case where `conda env update` hangs.
conda/conda pull request #11818
Opened 2022-09-09 06:51 UTC by fragmede

## Description
When using an environment.yml that asks pip to clone a git repo and that path exists, pip will ask for user input. As we are not in a context to provide such, tell pip what to do so it doesn't hang on waiting for user input.

### Setup:

environment.yml has
```
name: exists
dependencies:
  - python
  - pip
  - pip:
    - -e git+https://github.com/conda/conda
 ```

1. Run `conda env create`.
1. Run `conda env update`.

The env create runs fine. The conda env update, however, will hang while displaying a spinner . Hacking the code to [say what it's doing](https://github.com/fragmede/conda/commit/e4862e20508b75144e067be0aba3ce0e122565e7) show that the pip process is asking for user input:  `What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup`, which corresponds to the files existing. See the [pip documentation](https://pip.pypa.io/en/stable/cli/pip/#exists-action-option).

This patch force specifies that we want to backup the existing files and prevents pip from asking for user input in this specific case.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2022-09-12 21:04 UTC, kenodegard requested changes
@fragmede a reasonable addition, please include a news snippet and this should be good to go

2022-09-14 16:41 UTC, fragmede commented
@kenodegard I have added news file news/11818-conda-hang.

2022-09-23 10:09 UTC, jezdez approved these changes
This looks good, thank you!

2022-09-29 16:23 UTC, kenodegard requested changes
Minor documentation additions

2022-09-29 16:23 UTC, kenodegard commented on conda_env/installers/pip.py
> +        pip_cmd = ['install', '-U', '-r', requirements.name, '--exists-action=b']
```suggestion
        # see https://pip.pypa.io/en/stable/cli/pip/#exists-action-option
        pip_cmd = ['install', '-U', '-r', requirements.name, '--exists-action=b']
```

2022-09-29 16:23 UTC, kenodegard commented on news/11818-conda-hang
> +ask for user input for that case.  (#11818)
```suggestion
* `conda env update` would ask for user input and hang when working with pip
installs of git repos and the repo was previously checked out. Tell pip not to
ask for user input for that case.  (#11818)
```

2022-09-29 16:24 UTC, kenodegard approved these changes
@fragmede thanks for working on this, it's really appreciated 🚀

2022-09-29 19:56 UTC, merged