Download packages in parallel
conda/conda pull request #11841
Opened 2022-09-13 19:48 UTC by dholth

### Description

Download packages in parallel.

Anticipates thread-safe conda extract()

Progress bars currently overlap each other.

For #11608

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2022-09-14 12:31 UTC, dholth commented
Fetch threads should probably be 10 and extract threads 4 (informed by asv benchmark)

2022-09-14 16:14 UTC, dholth commented
The relevant benchmarks is https://dholth.github.io/conda-benchmarks/#conda_install.TimeInstall.time_explicit_install?branch=parallel-download&branch=main&x-axis=threads

When the latency is 0, the main branch is about as fast as this branch. When the latency increases, threading helps tremendously because we can wait for the per-package delays in parallel.

(We can't [extract in threads yet,](https://dholth.github.io/conda-benchmarks/#extract.TimeExtract.time_extract?branch=main&x-axis=threads) since libarchive is not threadsafe.)

2022-09-15 15:52 UTC, dholth commented
https://asciinema.org/a/7hf1BkGd8ZdUsXW8qx85Wl4Zt

2022-09-27 07:37 UTC, FFY00 commented
Hey, any ETA on merging this? This conflicts with #11600, and I think it's easier to just implement the plugin hook on top of this directly instead of resolving conflicts later.

2022-09-27 15:15 UTC, jezdez approved these changes
Just a few questions.. LGTM otherwise.

2022-09-27 15:17 UTC, dholth commented on conda/core/package_cache_data.py
> +from concurrent.futures.thread import ThreadPoolExecutor as Executor
We should add a get_executor / executor factory that chooses the right one (or a DummyExecutor when threads are disabled). However I need to double check that the DummyExecutor supports all the features I use.

2022-09-27 15:17 UTC, jezdez commented on conda/core/package_cache_data.py
> +        exceptions.append(e)
```suggestion
def done_callback(future, actions, progress_bar: ProgressBar, exceptions: list, finish=False):
    try:
        future.result()
    except Exception as e:
        do_reverse(progress_bar, *reversed(actions))
        exceptions.append(e)
```

2022-09-28 13:27 UTC, dholth commented on conda/core/package_cache_data.py
> +from concurrent.futures.thread import ThreadPoolExecutor as Executor
Used original name.

2022-09-29 10:36 UTC, travishathaway requested changes
Looking good so far, I would just like to see some doc strings added and we could also improve the readability with some better usage of type hints. There were also a couple of functions with unused arguments that need to be updated.

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
>              # TODO: use logger
It would be really nice to have a doc string in this method explaining what is going on at a high level.

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
> +    # dummy action to simplify code
```suggestion
def do_cache_action(prec, cache_axn, progress_bar, download_total=1.0):
    """
    This is function gets called from `ProgressiveFetchExtract.execute`
    """
    # dummy action to simplify code
```

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
> +    if not cache_axn:
cache_action? Not sure what `axn` means. Let's remove that ambiguity.

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
> +    # dummy action to simplify code
Please feel free to add whatever else you think would be important as a doc string. Perhaps even mention that it is getting called from within a `ThreadPoolExecutor` (right?)

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
> +def do_extract_action(prec, extract_axn, progress_bar):
This function signature leaves me wondering what the arguments are. Is this a place where type hinting could help? Also a doc string here would be very nice 🙏

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
> +def do_cleanup(progress_bar, *actions):
Looks like progress bar is an used argument. Could we remove it?

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
> +def do_reverse(progress_bar, *actions):
`progress_bar` is also unused here.

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
> +def done_callback(future, actions, progress_bar: ProgressBar, exceptions: list, finish=False):
```suggestion
def done_callback(future: Future, actions: tuple[Union[CacheUrlAction, ExtractPackageAction], ...], progress_bar: ProgressBar, exceptions: list[Exception], finish: bool = False):
```

Might as well go all the way if you're going to use type hints 😅 . If you decide to incorporate this change, be sure to add the following to the top of the file:

```python
from __future__ import annotations

from typing import Union
```

2022-09-29 10:36 UTC, travishathaway commented on conda/core/package_cache_data.py
> +def done_callback(future, actions, progress_bar: ProgressBar, exceptions: list, finish=False):
Also, this function would benefit from a doc string too 🙏

2022-09-29 12:04 UTC, travishathaway commented on conda/core/package_cache_data.py
> +    # dummy action to simplify code
Also, I that `cache_axn` variable should be spelled out `cache_action`. I know it's used else where in the code and you're just following convention, but it's a bad one that we should change 😄

2022-09-29 12:04 UTC, travishathaway commented on conda/core/package_cache_data.py
> +    if not cache_axn:
Realizing now that it's used else where in the code, but let's not follow a bad convention!

2022-09-29 20:53 UTC, dholth commented on tests/core/test_package_cache_data.py
> +        {"CONDA_USE_ONLY_TAR_BZ2": False, "CONDA_SUBDIR": "linux-64"},
It looks like this repository has plenty of subdirs but not osx-arm64

2022-09-30 12:35 UTC, travishathaway approved these changes

2022-09-30 12:35 UTC, merged

2023-02-06 08:22 UTC, imxtx commented
One drawback: The downloading process is not shown which is very misleading. I thought Conda was stuck.