Allow `conda init --dev` to output to either fd or tmp
conda/conda pull request #11865
Opened 2022-09-20 18:10 UTC by kenodegard

### Description

Expose controlling where `conda init --dev` is output. There are three ways to output:
- stdout (default)
- a file descriptor (e.g., `--fd 3`), or
- a (temp) file (e.g., `--tmp $TMPDIR/conda-init-dev.$$.$RANDOM`)

This way, the shell interface can choose how to receive the initialization script (as opposed to being told how it must receive it).

Depends on #11862 

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2022-10-04 16:41 UTC, jezdez submitted a review, later dismissed
Thank you for that refactor!

2022-10-05 23:23 UTC, kenodegard commented
pre-commit.ci autofix

2022-10-06 03:28 UTC, kenodegard commented on conda/cli/conda_argparse.py
> +    )
Defining a mutex group where all of the args are `SUPPRESS`-ed breaks sphinx...

2022-10-27 13:41 UTC, travishathaway requested changes
I noticed there's a lot of uncovered lines. Is there a way for to test this even if we have to use something like `subprocess.Popen`? I would feel a little better about this pull request if we could bump up the test coverage.

I'll be happy to be persuaded otherwise though if this represents a too big of a burden.

2023-06-15 01:59 UTC, kenodegard commented
this was a valuable learning and research effort but is unlikely to proceed in the current form

2023-06-15 01:59 UTC, closed without merging