Changing English on Skip Testing...
conda/conda pull request #12162
Opened 2022-12-08 17:19 UTC by sven6002

### Description

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

2022-12-09 12:27 UTC, travishathaway requested changes

2022-12-09 12:27 UTC, travishathaway commented on .github/workflows/tests-skip.yml
> +      - run: 'echo "No Source Changes and Skipping `test.yml`"'
```suggestion
      - run: 'echo "No source changes and skipping `test.yml`"'
```

Let's use title case here 😉

2022-12-12 14:13 UTC, sven6002 commented on .github/workflows/tests-skip.yml
> +      - run: 'echo "No Source Changes and Skipping `test.yml`"'
Perfect.. I'll change that..

2022-12-12 14:17 UTC, travishathaway approved these changes

2022-12-12 15:15 UTC, merged

2022-12-13 20:46 UTC, sven6002 commented
This is completed