lock stdout while writing json progress bar
conda/conda pull request #12233
Opened 2023-01-10 20:54 UTC by dholth

### Description

`sys.stdout` isn't threadsafe, leading to corrupted output. Lock while writing json progress bar substitute.

Fix #12225 #12231

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-01-10 20:55 UTC, dholth commented on conda/common/io.py
> +from .path import expand
sort imports

2023-01-11 22:16 UTC, dholth commented on conda/common/io.py
> +                    )
took the opportunity to format with black

2023-01-15 19:27 UTC, XuehaiPan commented on conda/common/io.py
> +            pass
`conda` now only supports Python 3.7+. We can guarantee `threading.RLock`.

2023-01-16 16:28 UTC, travishathaway commented
@dholth, did you try to write a test for this to recreate the failing condition. The code itself looks reasonable, but it would be nice to have a new test case covering it.

I understand testing threading issues may be pretty difficult in this context though...

2023-01-17 04:58 UTC, dholth commented
This is very easy to test manually, reliably corrupts output when piped into `tee`, correct output after locking added. We would need to pipe a parallel download to a file and assert no special characters - imo not a practical test.

2023-01-17 11:39 UTC, jezdez requested changes
This looks ready to go, except for the comment by @XuehaiPan about RLock being available in conda's 3.7+ world.

@dholth Could you elaborate about where tqdm says `threading.RLock` isn't always available?

2023-01-17 11:39 UTC, jezdez commented on conda/common/io.py
> +            pass
```suggestion
```

2023-01-17 11:39 UTC, jezdez commented on conda/common/io.py
> +from threading import Event, Lock, Thread
```suggestion
from threading import Event, Lock, RLock, Thread
```

2023-01-17 14:23 UTC, dholth commented
> 

https://github.com/tqdm/tqdm/blob/master/tqdm/std.py#L69

2023-01-17 14:23 UTC, dholth commented
I removed the RLock fallback since we require Python 3.7+

2023-01-17 17:25 UTC, jezdez approved these changes

2023-01-17 17:26 UTC, merged