disable user site-packages during de[activation]
conda/conda pull request #12438
Opened 2023-03-03 21:46 UTC by jjhelmus

### Description

Disable the user site-packages directory when retrieving the shell code for activation, deactivation and reactivation from CONDA_EXE. The output from these calls are evaluated by the shell and any extraneous output introduced by the user site-packages directory, such as by usercustomize.py or .pth files, will be evaluated.

An alternative would be to use Python in isolated mode (`-I`) to run the CONDA_EXE script. This would also ignore the PYTHON* environment variables and unsafe paths.

Note that this only adds this to Unix style shells.  Windows specific shells (cmd, powershell) may still access the user site-packages directory during activation.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [x] Add / update outdated documentation?

2023-03-06 15:14 UTC, jezdez commented
@jjhelmus Would you mind opening an issue please? We're trying to get away from PRs without prior record-keeping of what is being solved.

2023-03-06 17:26 UTC, jjhelmus commented
> @jjhelmus Would you mind opening an issue please? We're trying to get away from PRs without prior record-keeping of what is being solved.

Reported the issue in #12444

2023-03-06 18:01 UTC, jjhelmus commented
The failing test is a result of `conda` being [re-installed](https://github.com/conda/conda/actions/runs/4328144068/jobs/7557536999#step:3:170) from `defaults` during the setup in the associated job:
```
The following packages will be SUPERSEDED by a higher-priority channel:

  anaconda-client    conda-forge/noarch::anaconda-client-1~ --> pkgs/main/linux-64::anaconda-client-1.11.0-py310h06a4308_0 
  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.~ --> pkgs/main/linux-64::beautifulsoup4-4.11.1-py310h06a4308_0 
  certifi            conda-forge/noarch::certifi-2022.12.7~ --> pkgs/main/linux-64::certifi-2022.12.7-py310h06a4308_0 
  chardet            conda-forge::chardet-5.1.0-py310hff52~ --> pkgs/main::chardet-4.0.0-py310h06a4308_1003 
  conda              conda-forge::conda-23.1.0-py310hff520~ --> pkgs/main::conda-23.1.0-py310h06a4308_0

```  


This occurs in all the Linux conda-forge test jobs.  

Essentially these jobs are testing if the tests in this repo pass with the latest `defaults` conda package.  

This test behavior should be fixed so that the development version of conda is tested with conda-forge packages but is outside the scope of this PR.

2023-03-06 18:32 UTC, jezdez commented
BTW curious that chardet is older in main :-/

2023-05-04 13:37 UTC, jezdez commented
> @jezdez, are we still trying to get this in for the upcoming release? The tests look like they are passing (there's just a single random error).

Yeah, I think so, even though I'm not excited that this doesn't fix the Windows activation :-/

2023-06-06 10:58 UTC, jezdez commented
pre-commit.ci autofix

2023-06-15 01:50 UTC, kenodegard requested changes
the test as written passes on Windows without these changes so thats a false positive that should be removed

2024-10-22 04:02 UTC, closed without merging