Removing Python 3.7 from matrix.  Also, making exclude matrix on linu…
conda/conda pull request #12439
Opened 2023-03-03 21:57 UTC by ryanskeith

### Description

Addresses issue #12436 to drop Python 3.7 Support.

Also, sync's what is used in tests matrix in windows and linux section (which may have been on purpose).

2023-03-03 22:05 UTC, kenodegard requested changes

2023-03-03 22:05 UTC, kenodegard commented on .github/workflows/tests.yml
> +            python-version: '3.10'
I think this should stay 3.9:

```suggestion
            python-version: '3.9'
```

2023-03-06 14:09 UTC, jezdez approved these changes

2023-03-06 14:49 UTC, kenodegard approved these changes

2023-03-06 18:30 UTC, jezdez commented
Seems like #12446 might fix this.

2023-03-07 08:39 UTC, jezdez approved these changes

2023-03-07 08:39 UTC, merged