Mark conda._vendor.boltons for deprecation.
conda/conda pull request #12453
Opened 2023-03-07 10:14 UTC by jezdez

### Description

Xref #12272.

### Checklist - did you ...

- [[ ](url)] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- ~[ ] Add / update necessary tests?~
- ~[ ] Add / update outdated documentation?~

2023-03-07 16:26 UTC, kenodegard requested changes

2023-03-07 20:09 UTC, jezdez commented on conda/auxlib/entity.py
> +from boltons.timeutils import isoparse
Okay, do you mean all imports or just this one?

2023-03-08 10:02 UTC, jezdez commented on conda/auxlib/entity.py
> +from boltons.timeutils import isoparse
I've applied it to all.

2023-03-08 17:47 UTC, kenodegard approved these changes

2023-03-08 17:49 UTC, merged

2023-03-14 10:18 UTC, jaimergp commented
@conda/conda-core:

Note `subdir_data.py` is [still using the vendored copy](https://github.com/conda/conda/blob/8ff3ba1c06b9149855eeb48b9019a9ae7f45d3e2/conda/core/subdir_data.py#L23):

```
/opt/conda-src/conda/core/subdir_data.py:23: PendingDeprecationWarning: conda._vendor.boltons is pending deprecation and will be removed in 24.3. Use `boltons` instead.
    from conda._vendor.boltons.setutils import IndexedSet
```

We also need https://github.com/conda/conda/pull/12482 for better backwards compatibility