Indicate current shell when misconfigured
conda/conda pull request #12483
Opened 2023-03-14 08:50 UTC by johnyaku

### Description

On HPC systems, the shell used by the job scheduler may not always be the same as that used in interactive sessions. On our HPC, for example, the job scheduler uses `csh` while interactive sessions start in `bash`. This confuses users who may have configured, say, `~/.bashrc` to initialise conda but may not be aware that the job scheduler uses a different shell by default. These errors can be difficult to debug.

This PR includes the path to the current shell (taken from the `$SHELL` environment variable) in the error message. Hopefully this will make it easier to spot the fact that the current shell is not the expected shell, and to adjust the job submission flags accordingly.

This PR uses `os.popen()`. Not sure if this is best practice, but the spirit of the PR is to make these errors easier to debug. 

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

Don't think this change is big enough to warrant any of the above.

2023-05-04 11:40 UTC, travishathaway requested changes
Hi @johnyaku,

Thank you for submitting this pull request. I have a couple recommendations for improvement that I would like you to check out.

On top of those, another thing you should address is how this will appear for users on Windows. The process of determining the active running shell is a bit different; therefore, I don't think it's important to include. But, I would rather not have these users see empty parenthesis (e.g. `()`).

2023-05-04 11:40 UTC, travishathaway commented on conda/exceptions.py
> +            shell = os.popen('echo $SHELL').read().rstrip()
```suggestion
            shell = os.getenv("SHELL")
```

No need to open a sub process here. Was there a special reason you were doing that?

2023-05-04 11:40 UTC, travishathaway commented on conda/exceptions.py
> +            # Can be different in job schedulers versus interactive sessions, for example
```suggestion
```

It's not necessary to include these extra pieces of documentation. I believe it's pretty straightforward what's going on here.

2023-05-04 11:41 UTC, travishathaway commented
@johnyaku,

I have also updated this branch with the latest changes from main, so you will have to perform the following command to get everything working correctly locally for you:

```
git pull
```

2023-06-14 23:00 UTC, kenodegard commented
Unfortunately the `$SHELL` environment variable isn't a good indicator of what shell `conda` was invoked from (see https://stackoverflow.com/questions/55597797/detect-whether-current-shell-is-powershell-in-python/55598796#55598796)

2024-07-14 04:02 UTC, closed without merging