Add CITATION.cff
conda/conda pull request #12781
Opened 2023-06-08 17:08 UTC by schackartk

### Description

This pull request adds a CITATION.cff file to the root of the repository and would resolve #12779. As discussed in that issue, it provides several ways to help users cite conda. Hopefully this will help give conda it's due credit when it is used!

### Considerations

What information should be included in the citation file is up to the maintainers. I have done my best to fill out the information, but it can be difficult to know what to include (hence the need for such a file!)

A few things that I would suggest for further consideration:

- Who to list as authors? I see that conda does a good job of keeping updated lists. If it is possible to automate the task, it may be useful to add a full author list to the file and keep it up to date. Many projects use a broader approach like "The conda development team" or "Contributors to conda" to simplify this.
- What to use as the date? This is not required. It can be useful, but requires keeping it up to date.
- Should the version number be included in the file? Again, this is useful, but required more upkeep if it is not automated.

### Checklist - did you ...

- [X] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [X] Add / update necessary tests?
- [X] Add / update outdated documentation?

*Note*, I added it to the "Enhancements" section of the news template. Should it be that section, "Documentation", or "Other" instead?

2023-06-08 19:06 UTC, kenodegard commented
@conda-bot check

2023-06-08 19:07 UTC, kenodegard commented
pre-commit.ci autofix

2023-06-09 12:32 UTC, jezdez requested changes

2023-06-09 12:32 UTC, jezdez commented on CITATION.cff
> +  - name: "The conda development team"
Let's "contributors" here to acknowledge all kinds of contributions, not just code.
```suggestion
  - name: "conda contributors"
```

2023-06-09 12:32 UTC, jezdez commented on CITATION.cff
> +license: BSD 3 clause
The correct spelling of the license includes hyphens

```suggestion
license: BSD-3-clause
```

2023-06-14 08:37 UTC, merged