Remove arguments/`sys.argv` from pre/post_command actions
conda/conda pull request #12864
Opened 2023-07-11 05:13 UTC by kenodegard

### Description

Since we haven't solved the inconsistency of builtin subcommands passing a parsed `Namespace` and plugin subcommands passing an iterable of strings (i.e., `sys.argv`) this removes passing in the args into the pre/post command until we can properly identify a safe path forward.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-07-11 09:40 UTC, jezdez approved these changes
Just minor nitpicking

2023-07-11 09:40 UTC, jezdez commented on conda/plugins/manager.py
> +    def apply_pre_commands(self, command: str) -> None:
```suggestion
    def invoke_pre_commands(self, command: str) -> None:
```

If the docstring uses that term, let's use that verb :D

2023-07-11 09:40 UTC, jezdez commented on conda/cli/conda_argparse.py
> +        context.plugin_manager.apply_pre_commands(arguments.plugin_subcommand.name)
```suggestion
        context.plugin_manager.invoke_pre_commands(arguments.plugin_subcommand.name)
```

2023-07-11 09:40 UTC, jezdez commented on conda/cli/conda_argparse.py
> +        context.plugin_manager.apply_post_commands(arguments.plugin_subcommand.name)
```suggestion
        context.plugin_manager.invoke_post_commands(arguments.plugin_subcommand.name)
```

2023-07-11 09:40 UTC, jezdez commented on conda/cli/conda_argparse.py
> +    context.plugin_manager.apply_pre_commands(command)
```suggestion
    context.plugin_manager.invoke_pre_commands(command)
```

2023-07-11 09:40 UTC, jezdez commented on conda/cli/conda_argparse.py
> +    context.plugin_manager.apply_post_commands(command)
```suggestion
    context.plugin_manager.invoke_post_commands(command)
```

2023-07-11 13:37 UTC, kenodegard commented on tests/plugins/test_pre_command.py
> +    exc_message = "💥"
hehe just to make the pre and post tests symmetrical

2023-07-11 13:38 UTC, kenodegard commented on conda_env/cli/main.py
> +    context.plugin_manager.apply_post_commands(f"env_{command}")
```suggestion
    context.plugin_manager.invoke_post_commands(f"env_{command}")
```

2023-07-11 15:19 UTC, jezdez submitted a review, later dismissed

2023-07-13 15:46 UTC, travishathaway requested changes
@kenodegard, the documentation still needs to be updated:

- https://docs.conda.io/projects/conda/en/latest/dev-guide/plugins/post_commands.html
- https://docs.conda.io/projects/conda/en/latest/dev-guide/plugins/pre_commands.html

Those two pages still talk about passing the pre/post hook functions arguments.

Other than that, this pull request looks good to me.

2023-07-13 16:58 UTC, beeankha approved these changes

2023-07-14 08:14 UTC, travishathaway approved these changes
LGTM 🚀

2023-07-14 08:15 UTC, merged