Extract static pytest args into config
conda/conda pull request #13048
Opened 2023-08-29 03:45 UTC by kenodegard

### Description

Move all of the static pytest CLI args from the runtime scripts over into the config.

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

2023-08-29 06:56 UTC, jezdez requested changes

2023-08-29 06:56 UTC, jezdez commented on setup.cfg
Let's use this opportunity to move this into the [`pyproject.toml`](https://docs.pytest.org/en/7.3.x/reference/customize.html#pyproject-toml)

2023-08-29 06:56 UTC, jezdez commented on setup.cfg
(same for flake8)

2023-08-29 13:27 UTC, kenodegard commented on setup.cfg
`flake8` doesn't natively support `pyproject.toml` (see [docs](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations) and [original request response](https://github.com/PyCQA/flake8/issues/234#issuecomment-1206730688)), will need to use [`flake8-pyproject`](https://pypi.org/project/Flake8-pyproject/)

2023-08-29 19:30 UTC, jezdez commented on setup.cfg
*eyeroll* that flake8 ticket, I remember seeing it before

2023-08-29 19:31 UTC, jezdez commented on setup.cfg
What about resurrecting #12279?

2023-08-29 19:31 UTC, jezdez commented on setup.cfg
(obviously out of scope of this PR)

2023-08-29 22:54 UTC, kenodegard commented on setup.cfg
well for now I've combined it all using flake8-pyproject

happy to resurrect the ruff effort

2023-08-30 11:17 UTC, jezdez commented on setup.cfg
that's okay, let's not waste the effort, we can revisit ruff separately, maybe discuss it in the team again

2023-08-30 11:17 UTC, jezdez approved these changes

2023-08-30 11:18 UTC, jezdez commented
The test failures might be legit, any implicit config loading happening here?

2023-08-31 10:33 UTC, jezdez approved these changes

2023-08-31 10:33 UTC, merged