test_connection: use lighter-weight mock to test s3:// channels
conda/conda pull request #13085
Opened 2023-09-11 17:11 UTC by dholth

### Description

Since conda's usage of boto3 is limited, use a simpler mock server.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-09-11 22:23 UTC, dholth commented on tests/data/conda_format_repo/linux-64/current_repodata.json
> +      "sha256": "f33afff2144e1d6c4cf2e3e184937db8bf825b4537df74662aea5ee207b6a31b",
These hashes didn't match the test repository contents.

We'll see if any tests require the missing `libgcc-ng`.

2023-09-12 13:12 UTC, dholth commented on tests/gateways/test_connection.py
> +            boto3.session.Session.resource, "__defaults__", patched_defaults
This patch is the same as in `test_s3_server` using minio except for the url. It is used to point boto3 at a non-AWS server.

2023-09-12 14:01 UTC, dholth commented on tests/data/conda_format_repo/osx-64/repodata.json
> +      "sha256": "857293f389b188ba1fb02401a873fca5098db612ce6646c684efee77ad807f77",
I notice that previously the sha256 sum incorrectly matched that of the `.tar.bz2` version.

2023-09-12 20:32 UTC, kenodegard requested changes
this looks reasonable

we should combine `test_s2_server` and `test_s2_server_with_mock` before merging

2023-09-14 13:36 UTC, dholth commented
> this looks reasonable
> 
> we should combine `test_s2_server` and `test_s2_server_with_mock` before merging

I thought it might be a lot to combine both the new test, and all the work removing the old test and its associated scripts and caches in the same PR.

2023-09-25 17:41 UTC, jezdez commented
I've decided to go with #13084 for now to simplify our CI config, and then review this one again to make sure we're not risking test coverage.

2023-10-10 15:27 UTC, dholth commented on tests/cli/test_main_search.py
> +    stdout, _, _ = conda_cli("search", "--envs", "--json", search_for)
python was more likely to be found than conda

2023-10-10 18:34 UTC, beeankha commented
pre-commit.ci autofix

2023-10-19 20:18 UTC, beeankha approved these changes

2023-10-20 17:16 UTC, merged