More refactoring for plugin manager.
conda/conda pull request #13118
Opened 2023-09-18 11:53 UTC by jezdez

### Description

Following https://github.com/conda/conda/pull/13057/files#r1328506001 we noticed that #13057 removed the duplication check and makes the plugin loading prone to import time side effects.

### Checklist - did you ...

- ~[ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- ~[ ] Add / update necessary tests?~
- ~[ ] Add / update outdated documentation?~

2023-09-18 22:49 UTC, kenodegard requested changes
After reviewing `pluggy.PluginManager.register` again the only instances where a `ValueError` is raised is when the plugin has already been registered. Let's just silently consume this instead of converting it into a PluginError.

2023-09-19 18:46 UTC, kenodegard commented on conda/plugins/manager.py
> +                f"Error while loading first-party conda plugin: "
```suggestion
                f"Error while loading conda plugin: "
```

2023-09-19 18:46 UTC, kenodegard commented on conda/plugins/manager.py
> +                f"{self.get_canonical_name(plugin)} ({err})"
```suggestion
                f"{name or self.get_canonical_name(plugin)} ({err})"
```

2023-09-19 18:47 UTC, kenodegard commented on tests/plugins/test_subcommands.py
> +    plugin_manager.load_plugins(plugin2)
```suggestion
    assert plugin_manager.load_plugins(plugin2) == 0
```

2023-09-19 18:47 UTC, kenodegard commented on tests/plugins/test_subcommands.py
> +    plugin_manager.load_plugins(plugin)
```suggestion
    assert plugin_manager.load_plugins(plugin) == 0
```

2023-09-20 13:17 UTC, jezdez commented
Doc build error:

```
Running Sphinx v4.2.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/13118/lib/python3.10/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/13118/docs/source/conf.py", line 14, in <module>
    import conda
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/13118/conda/__init__.py", line 9, in <module>
    from .__version__ import __version__
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/13118/conda/__version__.py", line 4
    __version__ : str = version : str = '23.7.5.dev89'
                                ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/13118/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/13118/lib/python3.10/site-packages/sphinx/application.py", line 216, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/13118/lib/python3.10/site-packages/sphinx/config.py", line 172, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/13118/lib/python3.10/site-packages/sphinx/config.py", line 331, in eval_config_file
    raise ConfigError(msg % err) from err
sphinx.errors.ConfigError: There is a syntax error in your configuration file: invalid syntax (__version__.py, line 4)


Configuration error:
There is a syntax error in your configuration file: invalid syntax (__version__.py, line 4)

```

<img width="816" alt="CleanShot 2023-09-20 at 15 16 41@2x" src="https://github.com/conda/conda/assets/1610/0af43db1-417b-4496-a434-646c36dd00e4">

2023-09-25 16:46 UTC, kenodegard approved these changes

2023-09-25 17:08 UTC, merged