Add archspec dependency
conda/conda pull request #13213
Opened 2023-10-18 23:10 UTC by kenodegard

### Description

Xref https://github.com/conda-forge/conda-feedstock/pull/222

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

2023-10-19 08:29 UTC, jezdez requested changes
archspec on defaults is not up-to-date and I've requested an update to make sure we're in line with conda-forge.

Sadly, in [0.1.3](https://github.com/archspec/archspec/compare/v0.1.2...v0.1.3) something changed in how Apple Mx chips are detected, so `archspec.cpu.host()` doesn't return `arm64` anymore, but `m1`.

That means the call would not succeed, and we need to normalize the data.

2023-10-24 16:45 UTC, jezdez commented
archspec 0.2.1 is now on defaults

2023-10-26 15:33 UTC, jezdez approved these changes

2023-10-26 15:52 UTC, chenghlee approved these changes

2023-10-26 20:24 UTC, merged