Forward port 23.10.x into main.
conda/conda pull request #13286
Opened 2023-11-06 19:56 UTC by jezdez

### Description

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-11-06 20:15 UTC, kenodegard submitted a review, later dismissed

2023-11-07 03:06 UTC, kenodegard requested changes
Depends on https://github.com/conda/conda/pull/13289 and then resetting this PR from `23.10.x`

2023-11-08 16:21 UTC, kenodegard commented
@jezdez can we combine the two merge commits? want to keep the # of commits to a minimum since this will be merged without squashing

2023-11-08 17:31 UTC, dbast approved these changes

2023-11-09 14:47 UTC, kenodegard approved these changes

2023-11-09 14:51 UTC, merged