switching to conda-sphinx-theme
conda/conda pull request #13331
Opened 2023-11-15 11:50 UTC by travishathaway

### Description

Fixes: #13300 

This is the implementation for the `23.10.x` branch which will be identical to this open pull request:

- #13298

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-11-15 22:33 UTC, kathatherine commented on docs/source/configuration.rst
>  ===================
```suggestion
=============
```

2023-11-15 22:33 UTC, kathatherine commented on docs/source/dev-guide/plugins/health_checks.rst
> +Write new health checks using the ``health_checks`` plugin hook, install the plugins you wrote and they will run every time ``conda doctor`` command is run.
```suggestion
Write new health checks using the ``health_checks`` plugin hook, install the plugins you wrote, and they will run every time ``conda doctor`` command is run.
```

2023-11-15 22:33 UTC, kathatherine commented on docs/source/index.rst
> +Welcome to conda's documentation! Conda provides package, dependency and environment
```suggestion
Welcome to conda's documentation! Conda provides package, dependency, and environment
```

2023-11-15 22:33 UTC, kathatherine commented on docs/source/index.rst
> +        Follow this guide to get your own development environment set up.
```suggestion
        Follow this guide to get your own development environment set up
```

2023-11-15 22:33 UTC, kathatherine commented on docs/source/user-guide/index.rst
> +User Guide
Same capitalization question here as in the other PR.

2023-11-15 22:33 UTC, kathatherine commented on docs/source/index.rst
> +        Go in depth about environments and best practices for using them in your projects
Same comment as the other PR.

Got two "in depth"s here pretty close together. Maybe we could change the first one to "Go deeper with environments" or "Learn more about environments" or something similar.

2023-11-20 18:49 UTC, kathatherine approved these changes

2023-11-27 22:09 UTC, kenodegard requested changes

2023-11-27 22:09 UTC, kenodegard commented on docs/source/user-guide/tasks/manage-virtual.rst
> +  * ``__conda``: Version of conda that is being used for solving.
This is to be released in conda 23.11.0

```suggestion
```

2023-11-27 22:09 UTC, kenodegard commented on docs/source/_static/switcher.json
Do we not need this in https://github.com/conda/conda/pull/13298?

2023-11-28 15:57 UTC, travishathaway commented on docs/source/user-guide/tasks/manage-virtual.rst
> +  * ``__conda``: Version of conda that is being used for solving.
Good catch!

2023-11-28 16:16 UTC, travishathaway commented on docs/source/_static/switcher.json
Removed it!

2023-11-28 16:20 UTC, kenodegard commented on docs/source/dev-guide/plugins/health_checks.rst
Also not released yet (https://github.com/conda/conda/commit/c715853d48465c4f181d9a00051a53e52b0ec8f7)

2023-11-28 16:47 UTC, kenodegard approved these changes

2023-11-28 20:01 UTC, beeankha commented
The same issue [I mentioned](https://github.com/conda/conda/pull/13298#pullrequestreview-1753825392) in https://github.com/conda/conda/pull/13298 is showing up when I build these docs locally, though I'm not sure if it's something on my end or something that's fixable via this PR:

![Screenshot 2023-11-28 at 2 55 08 PM](https://github.com/conda/conda/assets/28930622/301f6b1c-8541-46d8-92af-4a57399c62eb)

2023-11-28 21:59 UTC, merged