add --keep-env flag
conda/conda pull request #13419
Opened 2023-12-11 22:24 UTC by ForgottenProgramme

### Description
Add a `--keep-env` flag to retain the environment when using `conda remove --all`

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2023-12-14 00:07 UTC, kenodegard commented on tests/cli/test_main_remove.py
> +def test_remove_all(tmp_env: TmpEnvFixture, conda_cli: CondaCLIFixture):
This is moved from `tests/test_create.py`, remember to delete the original

2023-12-14 00:11 UTC, kenodegard commented on tests/cli/test_main_remove.py
> +            conda_cli("remove", f"--prefix={prefix}", "python", "foo", "numpy")
`conda_cli` does not magically insert `--yes` like the older `run_command` implementation did so we need to be explicit

```suggestion
            conda_cli("remove", f"--prefix={prefix}", "python", "foo", "numpy", "--yes")
```

2023-12-14 00:11 UTC, kenodegard commented on tests/cli/test_main_remove.py
> +        conda_cli("remove", f"--prefix={prefix}", "--all")
```suggestion
        conda_cli("remove", f"--prefix={prefix}", "--all", "--yes")
```

2023-12-14 00:11 UTC, kenodegard commented on tests/cli/test_main_remove.py
> +        conda_cli("remove", f"--prefix={prefix}", "--all", "--keep-env")
```suggestion
        conda_cli("remove", f"--prefix={prefix}", "--all", "--keep-env", "--yes")
```

2023-12-15 02:01 UTC, kenodegard requested changes
`tmp_env` returns a `pathlib.Path` object so we should use it as such

2023-12-15 02:01 UTC, kenodegard commented on tests/cli/test_main_remove.py
> +
```suggestion
```

2023-12-15 02:01 UTC, kenodegard commented on tests/cli/test_main_remove.py
> +)
```suggestion
from conda.exceptions import PackagesNotFoundError
```

2023-12-15 02:01 UTC, kenodegard commented on tests/cli/test_main_remove.py
> +)
```suggestion
from conda.testing.integration import PYTHON_BINARY, package_is_installed
```

2023-12-15 11:09 UTC, travishathaway commented
@ForgottenProgramme,

I think it would be really nice to add an example to the help page:

https://github.com/conda/conda/blob/349ca85ce327ed76cfa514498f36d050c946b1ec/conda/cli/main_remove.py#L43-L58

2023-12-15 14:37 UTC, jezdez approved these changes

2023-12-15 14:51 UTC, travishathaway approved these changes

2023-12-15 14:59 UTC, beeankha approved these changes

2023-12-15 17:01 UTC, kenodegard approved these changes

2023-12-17 00:27 UTC, merged