Updating Miniconda links
conda/conda pull request #13572
Opened 2024-02-06 23:08 UTC by travishathaway

### Description

Fixes: #13571 

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-02-06 23:31 UTC, kenodegard approved these changes

2024-02-07 02:20 UTC, kenodegard requested changes
theres actually a few more instances of the old miniconda URL scattered throughout the code (not just in the docs), e.g.:
- https://github.com/conda/conda/blob/99902ee6914bead092f78842a81c5439758dd006/README.md#L32
- https://github.com/conda/conda/blob/99902ee6914bead092f78842a81c5439758dd006/HOW_WE_USE_GITHUB.md#L228 (to be updated within https://github.com/conda/infrastructure)

2024-02-07 17:17 UTC, travishathaway commented
@kenodegard,

Thanks for catching that. I will make the necessary updates.

2024-02-07 17:41 UTC, kenodegard requested changes
Some more:
- https://github.com/conda/conda/blob/12f301c5b7621464c8aaecdc6d913c6ba68b78d5/docs/source/glossary.rst?plain=1#L251
- https://github.com/conda/conda/blob/12f301c5b7621464c8aaecdc6d913c6ba68b78d5/docs/source/user-guide/install/linux.rst?plain=1#L7
- https://github.com/conda/conda/blob/12f301c5b7621464c8aaecdc6d913c6ba68b78d5/docs/source/user-guide/troubleshooting.rst?plain=1#L406

2024-02-07 23:58 UTC, travishathaway commented
@kenodegard,

Thanks for catching that. Ready for another look.

2024-02-08 00:58 UTC, kenodegard submitted a review, later dismissed

2024-02-08 14:53 UTC, beeankha commented on news/13572-conda-sphinx-docs-version-0-2-1
> +* Bump version of conda-sphinx-docs to 0.2.1 (#13572)
```suggestion
* Update the navigation links for Miniconda. (#13572)
```

2024-02-08 14:54 UTC, beeankha submitted a review, later dismissed
Other than the news file change suggestion, this LGTM!

2024-02-08 16:16 UTC, kenodegard approved these changes

2024-02-08 16:36 UTC, merged