change retry logic for 400 <= status < 500
conda/conda pull request #13576
Opened 2024-02-08 16:11 UTC by dholth

### Description

"Mark format as unavailable if code is in the 400's" 

This is about how it will look, but I feel this logic is not correct on the first commit. Do we need more than True/False? Should we show a different error if the /request/ type was `GET` or `Partial GET`?

Fix #13573 

#11638 

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-02-08 16:58 UTC, travishathaway commented
@dholth,

I haven't looked at this too in depth but my first thoughts are why isn't this being handled by something like:

- https://docs.python-requests.org/en/latest/user/advanced/#example-automatic-retries

It seems like this may be a cleaner way to handle it. Not sure if you've already considered it though.

2024-02-08 17:16 UTC, dholth commented
conda might be retrying certain errors in its networking stack?

But, a 404 is not one that needs to be retried, in this case we would like to move on to `repodata.json` when `repodata.json.zst` 404's or gives certain other error codes.

2024-02-08 19:46 UTC, kenodegard requested changes

2024-02-08 19:46 UTC, kenodegard commented on conda/gateways/repodata/jlap/fetch.py
> +    URL again next time.
```suggestion
def _http_retry(e: HTTPError) -> bool:
    """
    Return False if HTTPError is a fatal error, True if we should check the same
    URL again next time.
```

2024-02-08 19:46 UTC, kenodegard commented on conda/gateways/repodata/jlap/fetch.py
> +                if isinstance(e, HTTPError) and _http_error_no_retry(e):
```suggestion
                if not _http_retry(e):
```

2024-02-08 19:46 UTC, kenodegard commented on conda/gateways/repodata/jlap/fetch.py
> +            if isinstance(e, HTTPError) and _http_error_no_retry(e):
```suggestion
            if _http_retry(e):
```

2024-02-09 23:23 UTC, kenodegard commented on conda/gateways/repodata/jlap/fetch.py
> +    URL again next time.
```suggestion
    Determine whether the `HTTPError` is an HTTP 400 error code (except for 416).
```

2024-02-10 05:16 UTC, kenodegard approved these changes

2024-02-10 05:16 UTC, merged