Run macos tests on osx-64 and osx-arm64 runners
conda/conda pull request #13617
Opened 2024-02-22 10:50 UTC by dbast

### Description

Finally available for OSS projects: [GitHub Actions: Introducing the new M1 macOS runner available to open source!](
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-02-22 11:14 UTC, dbast commented
yay... the macos-14 runner are better available and seem to be really faster ... but some tests are failing.

2024-02-23 21:29 UTC, beeankha commented on news/13617-enable-osx-arm64-tests
> +  osx-arm64 canary builds. Fix / disable broken tests.
```suggestion
* Run Github Test workflow also on `osx-arm64` aka Apple Silicon Runners. Enable
  `osx-arm64` canary builds. Fix / disable broken tests. (#13617)
```

2024-02-26 14:59 UTC, jezdez requested changes

2024-02-26 14:59 UTC, jezdez commented on .github/workflows/tests.yml
> +        uses: conda/actions/canary-release@main
Let's do a tagged release first (I can do that later today)

2024-02-26 21:34 UTC, jezdez commented on .github/workflows/tests.yml
> +        uses: conda/actions/canary-release@main
```suggestion
        uses: conda/actions/canary-release@v24.2.0
```

2024-02-26 21:35 UTC, jezdez approved these changes

2024-02-26 23:38 UTC, merged