Add test that passes for existing behavior and fails for new behavior
conda/conda pull request #13779
Opened 2024-04-08 16:12 UTC by mattkram

### Description

Closes: #13778

Implements the ability to specify a URL prefix in `channel_settings.channel` instead of requiring an exact URL match. The only wildcard allowed is a suffix, e.g. `https://repo.some-hostname.com/*`. Because of this, the implementation explicitly avoids the complexity of using regex-based or `fnmatch`-based approaches.

### Example usage

Given the following `.condarc`, both specified channels would match the listed auth handler plugin:

```yaml
channels:
  - https://repo.some-hostname.com/some-channel
  - https://repo.some-hostname.com/some-other-channel

channel_settings:
  - channel: https://repo.some-hostname.com/*
    auth: some-auth-handler-plugin
```

### Testing notes

I have added an additional test which covers both cases of specifying an exact URL match and a prefix match. For this I have used `pytest.mark.parametrize` with named parametrizations.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-04-08 16:22 UTC, mcg1969 submitted a review, later dismissed

2024-04-08 16:37 UTC, intentionally-left-nil approved these changes

2024-04-08 19:14 UTC, jezdez requested changes
This needs to use a full pattern matching technique instead of special-casing the suffix given the non-trivial effort to fix the inevitable request to expand the scheme to path wildcards, subdomain wildcards etc in the future. I would suggest to use Python's fnmatch, assuming we can do a cross-check if there are security or performance concerns. We could pre-compile the patterns and cache them, if they aren't already in the stdlib variant.

To reduce the risk of downgrade attacks, I would suggest to not allow wildcards for the scheme portion of the channel URL (you have to spell out `http://` if you must).

2024-04-08 19:38 UTC, mattkram commented on tests/gateways/test_connection.py
> +    )
🤦 Definitely forgot to finish my refactor here. Thanks for the catch!

2024-04-08 19:49 UTC, intentionally-left-nil commented
@jezdez I think the `*` approach doesn't prevent a deeper regex pattern in the future. This is a nice balance of solving an immediate need with a specific usecase. But that's my 2 cents

2024-04-08 20:23 UTC, dholth commented
Could we re-use some kind of existing "browser cookie rules" engine to handle this and not regex?

2024-04-10 12:48 UTC, mattkram commented
@jezdez thank you for the feedback! I have implemented your recommendation. At a high level, we follow the following logic:

1. Check for exact match (existing behavior).
2. If that fails, we parse the channel URL and the target settings URL.
3. If the HTTP schema is missing from the pattern or not identical to the channel URL, we do not match
4. Otherwise, we check for a glob-like pattern match using `fnmatch`.

Please let me know if you think the test is over-parametrized. I'm trying to balance code duplication vs simplicity and I may be crossing a barrier where this should be two different tests.

2024-04-16 05:56 UTC, travishathaway approved these changes

2024-04-16 10:33 UTC, jezdez commented on conda/gateways/connection/session.py
> +            continue
Nice!

2024-04-16 10:34 UTC, jezdez approved these changes

2024-04-16 16:51 UTC, merged