Update disable-ssl-verification.rst
conda/conda pull request #13770
Opened 2024-04-06 00:01 UTC by dwr-psandhu

### Description

The SSL verification disabling works only with using conda config as described. (conda version 24.3.0). The environment variable method described doesn't work.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-04-08 11:21 UTC, travishathaway commented
@dwr-psandhu,

As previously stated by @conda-bot, we cannot review this pull request until you have signed the CLA agreement.

Also, please add a small description stating why you are suggesting these changes.

2024-04-08 15:51 UTC, dwr-psandhu commented
The SSL verification disabling works only with using conda config as described. (conda version 24.3.0). The environment variable method described doesn't work.

2024-04-08 15:54 UTC, dwr-psandhu commented
> We require contributors to sign our [Contributor License Agreement](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement) and we don't have one on file for @dwr-psandhu.
> 
> In order for us to review and merge your code, please e-sign the [Contributor License Agreement PDF](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement). We then need to manually verify your signature, merge the PR ([conda/infrastructure#910](https://github.com/conda/infrastructure/pull/910)), and ping the bot to refresh the PR.



> @dwr-psandhu,
> 
> As previously stated by @conda-bot, we cannot review this pull request until you have signed the CLA agreement.
> 
> Also, please add a small description stating why you are suggesting these changes.

Done.

2024-04-09 05:39 UTC, travishathaway commented
@conda-bot check

2024-04-09 05:40 UTC, travishathaway commented on docs/source/user-guide/configuration/disable-ssl-verification.rst
> +=============================================
```suggestion

=============================================
```

2024-04-09 05:42 UTC, travishathaway commented on docs/source/user-guide/configuration/disable-ssl-verification.rst
> +If the above doesn't work use
```suggestion
In addition to disabling SSL via environment variables, you can disable it by setting `ssl_verify` to `false` in your config files. To do so, run the following commands to disable and enable it: 
```

2024-04-09 05:43 UTC, travishathaway commented on docs/source/user-guide/configuration/disable-ssl-verification.rst
> +   # Do conda commands
```suggestion
   # Run conda commands with SSL disabled
```

2024-04-09 05:43 UTC, travishathaway requested changes
Please see my suggested changes.

2024-04-09 13:42 UTC, dwr-psandhu reviewed
Much better. Thanks and accepted.

2024-04-10 03:59 UTC, travishathaway approved these changes

2024-04-10 03:59 UTC, merged