Reporter and output handler plugin hooks
conda/conda pull request #13868
Opened 2024-04-26 10:22 UTC by travishathaway

### Description

Fixes: #13815

This pull request is still a draft.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-06-07 11:36 UTC, jezdez requested changes

2024-06-07 11:36 UTC, jezdez commented on conda/base/context.py
> +                    "stream": "stdout",
Nah, that's configuring an output, which has a stream feature, we shouldn't confuse these terms

2024-06-07 11:36 UTC, jezdez commented on conda/plugins/hookspec.py
> +    def conda_reporter_streams(self) -> Iterable[CondaReporterStream]:
Output is the better term for this, as it's generic enough to describe what it does, while the "stream" is the canonical term for a file-like object to write to

2024-06-10 11:48 UTC, jezdez requested changes
As-is this couples the different layers too deeply, please consider my proposed refactor in https://github.com/travishathaway/conda/pull/3 so we can separate data to render from the style to render it with.

2024-06-10 11:48 UTC, jezdez commented on conda/cli/main_info.py
> +def get_display_data(
Let's refactor this in the way I suggested please, since it unnecessarily mixes the data to render with the style to render with in the return type.

2024-06-19 09:06 UTC, jezdez reviewed
Ultimately, I'm not convinced this sufficiently decouples the new reporter rendering from the CLI argument. But this is getting old, and I don't know what to say else to convince you to better separate CLI from output rendering, so treat the comments related to that as future optimizations (please file tickets about them).

Thank you for accepting my suggestions around naming and design of the reporter backends and outputs, some of the files still have the old name with "handler", and the tests need to be updated as well.

2024-06-19 09:06 UTC, jezdez commented on conda/plugins/hookspec.py
> +                   description="Output handler that writes output to a file",
```suggestion
                   description="Reporter output that writes to a file",
```

2024-06-19 09:06 UTC, jezdez commented on conda/plugins/manager.py
> +                return handler
```suggestion
        for reporter_backend in self.get_reporter_backends():
            if reporter_backend == name:
                return reporter_backend
```

2024-06-19 09:06 UTC, jezdez commented on conda/plugins/manager.py
> +                return handler
```suggestion
        for reporter_output in self.get_reporter_outputs():
            if reporter_output.name == name:
                return reporter_output
```

2024-06-19 09:06 UTC, jezdez commented on conda/plugins/reporter_backends/console.py
> +This reporter handler provides the default output for conda.
```suggestion
Defines a "console" reporter backend.

This reporter backend provides the default output for conda.
```

2024-06-19 09:06 UTC, jezdez commented on conda/plugins/reporter_backends/json.py
> +    that can be passed to reporter streams .
```suggestion
    that can be passed to reporter outputs.
```

2024-06-19 09:06 UTC, jezdez commented on news/13868-reporter-and-output-handler-plugin-hooks
> +* Adds two new plugin hooks for reporter handlers and output handlers (#13868)
```suggestion
* Adds two new plugin hooks for reporter backends and reporter output. (#13868)
```

2024-06-19 12:43 UTC, travishathaway commented on conda/common/io.py
> +
No. Will remove.

2024-06-19 12:46 UTC, travishathaway commented on conda/plugins/hookspec.py
> +           from conda.plugins.types import CondaReporterOutput
Will add. Wasn't sure how detailed to make these examples.

2024-07-16 11:34 UTC, travishathaway commented
@jezdez,

I made some changes to this today to incorporate recent changes in main that revert the usage of the `--verbose` option in favor of the `--all` option.

More information: https://github.com/conda/conda/pull/14004

2024-07-23 08:15 UTC, jezdez approved these changes
This looks good to go!

Really appreciative for your patience with my feedback @travishathaway!

2024-07-23 10:55 UTC, merged