Add a `keep_case` flag which ensures that env variables are not uppercased
conda/conda pull request #13904
Opened 2024-05-08 11:04 UTC by ForgottenProgramme

### Description
At present `conda` converts all environment variables into uppercase. 
This PR adds a `keep_case` context variable, which allows users to store their environment variables as is.

The original behavior i.e conda uppercasing the env var is maintained. 
Therefore when a new env variable is added using the `keep_case` flag, two new environment variables will be created and saved: one with all letters uppercase, and one with lowercase (or the combination of cases used by the user i.e. the user's intended case will be "kept"). This ensures that nothing breaks. 

**Tasks**

- [ ] Add a new `keep_case` variable to context
- [ ] store environment variables in original case when `keep_case` is `True`
- [ ] write tests

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-05-13 13:40 UTC, ForgottenProgramme commented
pre-commit.ci autofix

2024-05-14 16:30 UTC, kenodegard requested changes

2024-05-14 16:30 UTC, kenodegard commented on tests/test_activate.py
> +    assert "FOUR" in unset_vars
Combine both of these with parameterization:

```suggestion
@pytest.mark.parametrize("keep_case", [True, False])
def test_keep_case(monkeypatch: MonkeyPatch, keep_case: bool):
    monkeypatch.setenv("CONDA_KEEP_CASE", keep_case)
    reset_context()
    assert context.keep_case is keep_case

    activator = PosixActivator()
    export_vars, unset_vars = activator.get_export_unset_vars(
        one=1,
        TWO=2,
        three=None,
        FOUR=None,
    )

    # original lowercase (conditionally true per keep_case)
    assert ("one" in export_vars) is keep_case
    assert ("three" in unset_vars) is keep_case

    # to uppercase (always true)
    assert "ONE" in export_vars
    assert "THREE" in unset_vars

    # original uppercase (always true)
    assert "TWO" in export_vars
    assert "FOUR" in unset_vars
```

2024-05-14 16:30 UTC, kenodegard commented on tests/test_activate.py
> +    assert "THREE" in unset_vars
Do the same here

2024-05-14 16:30 UTC, kenodegard commented on conda/activate.py
> +                        export_vars[name] = self.path_conversion(value)
This clause is untested in `test_metavars_keep_case`. Let's adjust the mocked value for `context.conda_exe_vars_dict` to include a path-like value.

2024-05-20 19:05 UTC, kenodegard requested changes

2024-05-20 19:07 UTC, kenodegard commented on tests/test_activate.py
> +        "SIX": "a\\path",
`SIX` is not included in the assertions below

2024-06-07 08:51 UTC, jezdez commented
Close in favor of #13943.

2024-06-07 08:51 UTC, closed without merging