Fix `test_env_export_json` test and update `main_remove.py` to not delete parent empty directories
conda/conda pull request #14173
Opened 2024-08-23 16:22 UTC by beeankha

### Description

While working on [Alias `conda env remove` command to `conda remove --all` # 13977](https://github.com/conda/conda/pull/13977) I came across a mysterious test failure in `tests/cli/test_env.py::test_env_export_json`. It appeared that the `conda env export` command was previously able to access a deleted environment (when using the unaliased `conda env remove`), which showed that `conda env remove` was not as robust as `conda remove` (this has been reported in #11092).

This PR:
- updates `main_remove.py` to no longer remove empty parent directories when deleting environments, since this could lead to some unpleasant surprises for a user's conda setup
- edits `tests/cli/test_env.py::test_env_export_json` to use the `path_factory` fixture, which removes the need for invoking the `conda env remove` command to clean up the temporary prefix
- changes the order of the assertions in `tests/cli/test_env.py::test_env_export_json` since previously `conda env export` was being run on a non-existent environment and the test should _not_ have been passing
- adds an extra `spec_str.count("=") == 2` check to ensure that the [regression test](https://github.com/conda/conda/pull/6221/files#diff-79e04d67165171f3581c753e3e5a14a84a8417767bf212fe3ac8cb19e9e8823cR267-R274) related to #6220 is still included

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [ ] ~~Add / update outdated documentation?~~

2024-08-23 16:24 UTC, beeankha commented on conda/cli/main_remove.py
> -                rm_rf(prefix, clean_empty_parents=True)
This line was added 5 years ago in [this PR](https://github.com/conda/conda/pull/8134/files#diff-54eebab3b20edeedd664816e6d8ae990d901f7b1eb2c4c41f876ba3394bc7189R57), for reference.

2024-08-23 20:36 UTC, kenodegard commented on conda/cli/main_remove.py
> -
shouldn't attempting to remove a non-existent env fail? currently it silently succeeds which is confusing:

<img width="805" alt="Screenshot 2024-08-23 at 15 34 57" src="https://github.com/user-attachments/assets/03d5d697-4e16-4272-850d-8ec72f8b2c1c">

2024-08-23 20:37 UTC, kenodegard commented on conda/cli/main_remove.py
> -
Not something that needs to be addressed here, we should open a separate issue for this.

2024-08-23 20:39 UTC, beeankha commented on conda/cli/main_remove.py
> -
Yes I noticed that attempting to remove a non-existent env doesn't produce an error while working on #13977, will definitely be addressing this in a separate PR.

2024-08-23 20:40 UTC, kenodegard commented on conda/cli/main_remove.py
> -
just opened a new issue to track this: https://github.com/conda/conda/issues/14174

2024-08-23 20:40 UTC, kenodegard approved these changes

2024-08-23 20:44 UTC, beeankha commented on conda/cli/main_remove.py
> -
I'll revert this change for this PR and remove this comment when working on #14174

2024-08-23 20:44 UTC, kenodegard commented on tests/cli/test_env.py
> +    assert Path(prefix).exists()
should use `tmp_env` instead here?

2024-08-23 21:06 UTC, kenodegard requested changes

2024-08-23 21:06 UTC, kenodegard commented on tests/cli/test_env.py
> +        assert Path(prefix).exists()
```suggestion
    with tmp_env("zlib") as prefix:
```

2024-08-23 22:41 UTC, kenodegard submitted a review, later dismissed

2024-08-23 22:42 UTC, kenodegard commented
pre-commit.ci autofix

2024-08-23 22:43 UTC, kenodegard approved these changes

2024-08-26 11:47 UTC, travishathaway approved these changes

2024-08-26 12:04 UTC, ForgottenProgramme approved these changes

2024-08-26 12:29 UTC, merged