Error nonexistent env removal
conda/conda pull request #14199
Opened 2024-08-29 18:33 UTC by beeankha

### Description

To resolve https://github.com/conda/conda/issues/14174

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

2024-09-17 16:28 UTC, kenodegard commented on conda/cli/main_remove.py
> +    if args.all and not is_conda_environment(prefix):
Don't we _always_ want to check if the prefix is valid? Shouldn't it still fail here if I say `conda remove -n missing zlib`?

2024-09-17 16:40 UTC, kenodegard commented on tests/cli/test_env.py
> +        assert is_conda_environment(prefix)
This isn't testing what it's supposed to test. Breaking it down:
1. `with tmp_env() as prefix`: creates an empty environment
2. `create_env(ENVIRONMENT_CA_CERTIFICATES)`: creates an `environment.yml` file
3. `assert is_conda_environment(prefix)`: ensures the env from 1. exists

The env file from 2. is never used!

We're gonna want something like this instead:

```suggestion
    create_env(ENVIRONMENT_CA_CERTIFICATES)
    prefix = path_factory()
    conda_cli(
        "env",
        "create",
        f"--prefix={prefix}",
        # "--file=environment.yml",  # the implicit default
    )
    assert is_conda_environment(prefix)
    assert package_is_installed(prefix, "ca-certificates")
```

2024-09-17 16:45 UTC, kenodegard requested changes
One concern I have with the tests is how most are writing a `environment.yml` file into my CWD via the `create_env` helper function. Let's use something like `monkeypatch.chdir(tmp_path)` to avoid side effects and keep our CWD clean.

2024-09-24 11:33 UTC, jezdez approved these changes

2024-09-24 22:14 UTC, kenodegard approved these changes

2024-09-24 22:48 UTC, merged